version: "2"
services:
    api:
        image: node:12.20
        command: npm run start:dev
        working_dir: /app
        volumes:
            - $PWD:/app
        ports:
            - "3000:3000"
    db:
        image: postgres:12.0
        environment:
            POSTGRES_DB: "app"
            POSTGRES_USER: "appuser"
            POSTGRES_PASSWORD: "apppass"